### ISSUE TITLE
SOLVED: Iso/Surface Value

### ISSUE THREAD

**Issue by MusoAga** [bbtarzan12/Marching-Cubes#1]
Hey, very cool project! I have a question about the MC. 

[Here](http://paulbourke.net/geometry/polygonise/) we can see, that there is a Isovalue, to determine which value is in and out of the surface. Where in your code takes this place? 

Thanks!

**Comment by MusoAga** [comment]
Solved: 

Add Isovalue to this code in GenerateMarchingCubes

`if (densities[i] < Isovalue)`

and VectorInterp function:

`if (Mathf.Abs(isovalue - v0) < 0.00001f)`
`if (Mathf.Abs(isovalue - v1) < 0.00001f)`
`float mu = (isovalue - v0) / (v1 - v0);`

**Comment by bbtarzan12** [comment]
I'm glad the problem is solved!

The code assumes Isovalue as 0.
